### ISSUE TITLE
Feature request: Organize child objects of the tile prefabs in a more nested hierarchy

### ISSUE THREAD

**Issue by oyvind-stromsvik** [briochie/wow.unity#8]
You can get thousands, if not tens of thousands child objects for the tile prefabs, and currently they are all the immediate children of the tile prefab.

In my current project I've made an empty child game object for "chunks" and one for "prefabs" as child game objects for each tile prefab, and put the respective game objects under there, but it would probably be even better to have "trees", "rocks", "bushes", "buildings" etc. under the prefabs folder as well.

These "mega prefabs" are exceptionally heavy to work with in general. Just toggling or deleting a child object will lead to Unity taking upwards of 15-20 seconds before allowing me to perform a new action. I doubt a more nested hierarchy does anything to alleviate this though, but in my project I've unpacked all the tile prefabs so that I only have prefabs for the actual instanced objects. This makes working in the scene view instant by comparison. Since the tiles are unique it doesn't really make sense for them to be prefabs to begin with, but it's maybe the only way for you to correctly place all the objects on the terrain in a way that the end user can access? This was a bit of a tangent. I'm just thinking out loud :p

**Comment by briochie** [comment]
Also something I was working on! Originally I had difficulty getting the doodads in a hierarchy I was happy with, but now with the water implementation, I found how to work around that.

**Comment by briochie** [comment]
A new PR added some time ago adds this. I'll evaluate that feature when I review that PR.
