### ISSUE TITLE
Feature request: Liquid support

### ISSUE THREAD

**Issue by oyvind-stromsvik** [briochie/wow.unity#9]
I assume liquid in terms of the wow.export exporter means lakes, rivers etc. 

So far I've just used Probuilder inside Unity to manually create somewhat correct looking meshes for these and it works fine, but I assume it's possible to parse the liquid data exported from wow.export and programmatically create these meshes at import.

Not sure if this is a wow.export issue though? I get that there's a lot more to liquids than just the mesh in WoW, but I would imagine the main thing is the mesh, and wow.export could probably create the mesh on export as well?

**Comment by briochie** [comment]
This was something I was actively working on before I lost access to my computer space. Planning to pick this up again when I'm able.

**Comment by briochie** [comment]
Will likely revisit this in a future feature. As of right now, not planned on the immediate roadmap.
